import type { AppManifest } from '@nexos/types';

const systemPermissions: AppManifest['permissions'] = [
  'filesystem.read',
  'filesystem.write',
  'notifications',
  'system.settings',
  'process.read',
  'process.kill',
  'clipboard',
];

export const builtInManifests: readonly AppManifest[] = [
  {
    id: 'com.nexos.shell',
    name: 'NexOS Shell',
    description: 'The trusted NexOS desktop shell.',
    version: '0.2.0',
    icon: 'nexos',
    entry: 'shell',
    runtime: 'builtin',
    permissions: systemPermissions,
    singleInstance: true,
    system: true,
    defaultWidth: 1024,
    defaultHeight: 720,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.files',
    name: 'Files',
    description: 'Browse and manage the NexOS virtual filesystem.',
    version: '1.0.0',
    icon: 'folder',
    entry: 'files',
    runtime: 'builtin',
    permissions: ['filesystem.read', 'filesystem.write'],
    singleInstance: false,
    system: true,
    defaultWidth: 980,
    defaultHeight: 650,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.terminal',
    name: 'Terminal',
    description: 'A command-driven interface to NexOS services.',
    version: '1.0.0',
    icon: 'terminal',
    entry: 'terminal',
    runtime: 'builtin',
    permissions: systemPermissions,
    singleInstance: false,
    system: true,
    defaultWidth: 850,
    defaultHeight: 540,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.settings',
    name: 'Settings',
    description: 'Personalize and secure NexOS.',
    version: '1.0.0',
    icon: 'settings',
    entry: 'settings',
    runtime: 'builtin',
    permissions: ['system.settings', 'process.read'],
    singleInstance: true,
    system: true,
    defaultWidth: 940,
    defaultHeight: 650,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.notes',
    name: 'Notes',
    description: 'Capture ideas with safe autosave.',
    version: '1.0.0',
    icon: 'notebook',
    entry: 'notes',
    runtime: 'builtin',
    permissions: ['filesystem.read', 'filesystem.write', 'notifications'],
    singleInstance: true,
    system: false,
    defaultWidth: 780,
    defaultHeight: 600,
    fileExtensions: ['.note'],
  },
  {
    id: 'com.nexos.calculator',
    name: 'Calculator',
    description: 'A precise, keyboard-friendly calculator.',
    version: '1.0.0',
    icon: 'calculator',
    entry: 'calculator',
    runtime: 'builtin',
    permissions: [],
    singleInstance: true,
    system: false,
    defaultWidth: 390,
    defaultHeight: 560,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.text-editor',
    name: 'Text Editor',
    description: 'Edit text, Markdown, JSON, and source files.',
    version: '1.0.0',
    icon: 'file-text',
    entry: 'text-editor',
    runtime: 'builtin',
    permissions: ['filesystem.read', 'filesystem.write', 'notifications'],
    singleInstance: false,
    system: false,
    defaultWidth: 900,
    defaultHeight: 650,
    fileExtensions: ['.txt', '.md', '.json', '.html', '.css', '.js', '.ts'],
  },
  {
    id: 'com.nexos.image-viewer',
    name: 'Image Viewer',
    description: 'View images stored in NexOS.',
    version: '1.0.0',
    icon: 'image',
    entry: 'image-viewer',
    runtime: 'builtin',
    permissions: ['filesystem.read'],
    singleInstance: false,
    system: false,
    defaultWidth: 880,
    defaultHeight: 620,
    fileExtensions: ['.png', '.jpg', '.jpeg', '.gif', '.svg'],
  },
  {
    id: 'com.nexos.task-manager',
    name: 'Task Manager',
    description: 'Inspect performance and control processes.',
    version: '1.0.0',
    icon: 'activity',
    entry: 'task-manager',
    runtime: 'builtin',
    permissions: ['process.read', 'process.kill'],
    singleInstance: true,
    system: true,
    defaultWidth: 840,
    defaultHeight: 600,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.app-manager',
    name: 'App Manager',
    description: 'Install and manage safe NexOS application packages.',
    version: '1.0.0',
    icon: 'package',
    entry: 'app-manager',
    runtime: 'builtin',
    permissions: ['filesystem.read', 'filesystem.write', 'system.settings'],
    singleInstance: true,
    system: true,
    defaultWidth: 850,
    defaultHeight: 610,
    fileExtensions: ['.nxapp'],
  },
  {
    id: 'com.nexos.system-info',
    name: 'System Information',
    description: 'Runtime, hardware, and storage information.',
    version: '1.0.0',
    icon: 'cpu',
    entry: 'system-info',
    runtime: 'builtin',
    permissions: ['process.read'],
    singleInstance: true,
    system: true,
    defaultWidth: 720,
    defaultHeight: 560,
    fileExtensions: [],
  },
  {
    id: 'com.nexos.nexai',
    name: 'NexAI',
    description: 'A tool-based assistant for safe NexOS actions.',
    version: '1.0.0',
    icon: 'sparkles',
    entry: 'nexai',
    runtime: 'builtin',
    permissions: ['filesystem.read', 'notifications', 'system.settings'],
    singleInstance: true,
    system: true,
    defaultWidth: 760,
    defaultHeight: 620,
    fileExtensions: [],
  },
] as const;
